### ISSUE TITLE
support the -preserve flag

### ISSUE THREAD

**Issue by mjibson** [thepudds/fzgo#10]
When fuzzing certain packages of cockroachdb, I need to use this flag (may be something related to our protobuf compiler) to disable a few packages. Would be nice to have it available to fzgo.

https://github.com/dvyukov/go-fuzz/pull/268

**Comment by thepudds** [comment]
Hello @mjibson, thanks for taking the time to file this suggestion.

I hopefully addressed it in PR #12. If you update to the latest version of `fzgo`, you should now be able to use the `FZGOFLAGSBUILD` environment variable to pass additional arguments to `go-fuzz-build`. 

For your particular case, you should be able to do something like:

```
$ export FZGOFLAGSBUILD=-preserve=foo,bar
$ fzgo test -fuzz=. ./...
```

Please let me know if that works for you. To aid with future experimentation, you can pass extra args to `go-fuzz-build` via `FZGOFLAGSBUILD` and `go-fuzz` via `FZGOFLAGSFUZZ`. Those two env vars both support a whitespace-separated list of arguments to pass through.

Finally, I would be very interested to hear any other feedback you might have in general on this or anything else.

Thanks again!
